# uballoc-config.cmake — for downstream find_package(uballoc CONFIG REQUIRED)
#
# Exposes the imported target  uballoc::uballoc  (shared library + headers).
# Generated by `cmake --install` into lib/cmake/uballoc/.
#
# Usage in a downstream project:
#   find_package(uballoc CONFIG REQUIRED)
#   target_link_libraries(my_app PRIVATE uballoc::uballoc)
#
# The ubse-client dependency (when UBSE backend is built) is resolved via
# find_library below — the exported target may reference "ubse-client" as
# a CMake target name that downstream doesn't have, so we resolve it to
# a full library path and override the interface link dependency.

include("${CMAKE_CURRENT_LIST_DIR}/uballoc-targets.cmake")

# Force C++17 on the imported target — CMake's install(EXPORT) doesn't reliably
# propagate INTERFACE_CXX_STANDARD, so downstream projects that don't set
# CMAKE_CXX_STANDARD themselves would fall back to the compiler default (C++14
# on GCC 12), and the uballoc headers (which use C++17 features) would fail
# to compile. target_compile_features(INTERFACE) is the modern, reliable way
# to propagate the requirement to any consumer linking against this target.
target_compile_features(uballoc::uballoc INTERFACE cxx_std_17)

# Optional: surface the backend choice as a cached variable downstream can
# inspect. 1 = UBShmProvider (UBSE), 0 = PosixShmProvider (/dev/shm).
set(UBALLOC_USE_UBSE @UBALLOC_USE_UBSE@)

# For UBSE builds, resolve ubse-client to a library path. The exported
# target records "ubse-client" in INTERFACE_LINK_LIBRARIES, but downstream
# users may not have a CMake target by that name. find_library resolves it
# to a path like /usr/lib64/libubse-client.so, which the linker can use
# directly.
if(UBALLOC_USE_UBSE)
    find_library(_UBALLOC_UBSE_CLIENT ubse-client)
    if(_UBALLOC_UBSE_CLIENT)
        set_property(TARGET uballoc::uballoc PROPERTY
            INTERFACE_LINK_LIBRARIES "${_UBALLOC_UBSE_CLIENT}"
        )
    endif()
    unset(_UBALLOC_UBSE_CLIENT CACHE)
endif()

# Convenience: a variable form for projects that prefer it.
set(UBALLOC_LIBRARIES uballoc::uballoc)
